Repository IU-Softwareengineering/KMI_System, pull requests merged in 2024-05, with the labels that each got.

#1 Material bludwell
  src/main/java/com/iu/kmi/Material.java
Labels: feature, G_SDK

#7 Erstellung Klasse Lager
  src/main/java/Lager.java
Labels: feature, G_SDK

#4 Kunden Class und Kunden VerwaltungsClass und Adresse Class
  src/main/java/Classes/Adresse.java
  src/main/java/Classes/Kunde.java
  src/main/java/Classes/KundenVerwaltung.java
Labels: G_SDK

#8 Move Lager class to package dir
  src/main/java/com/iu/kmi/Lager.java
Labels: bug, G_SDK
