Repository IU-Softwareengineering/KMI_System, pull requests merged in 2024-06, with the labels that each got.

#9 adding class Angebot and JUintTest
  pom.xml
  src/main/java/JUint_tests/AngebotTest.java
  src/main/java/com/iu/kmi/Angebot.java
Labels: G_BDK

#10 Class Lager - id als String
  src/main/java/com/iu/kmi/Lager.java
Labels: documentation, G_SDK

#11 Started implementing support for composite primary keys, fixed file structure
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  src/main/java/com/iu/kmi/database/annotations/CompositeKey.java
  src/main/java/com/iu/kmi/database/orm/query/BaseQuery.java
  src/main/java/com/iu/kmi/entities/Adresse.java
  src/main/java/com/iu/kmi/entities/Angebot.java
  src/main/java/com/iu/kmi/entities/Kunde.java
  src/main/java/com/iu/kmi/entities/KundenVerwaltung.java
  src/main/java/com/iu/kmi/entities/Lager.java
  src/main/java/com/iu/kmi/entities/Material.java
  src/main/java/com/iu/kmi/test/AngebotTest.java
Labels: feature, G_DB

#14 Kundenanfrage
  src/main/java/com/iu/kmi/entities/Kundenanfrage.java
  src/main/java/com/iu/kmi/test/KundenanfrageTest.java
Labels: feature, G_BDK

#13 Initial Kondition and KonditionTest class
  src/main/java/com/iu/kmi/entities/Kondition.java
  src/main/java/com/iu/kmi/test/KonditionTest.java
Labels: feature, G_SDK

#15 Database: Add Documentation Files
  doc/schema.dbml
  doc/schema.sql
Labels: documentation, G_DB

#16 BDK1 Auftrag + Auftragsposition
  src/main/java/com/iu/kmi/entities/Auftrag.java
  src/main/java/com/iu/kmi/entities/AuftragsPosition.java
  src/main/java/com/iu/kmi/test/AuftragTest.java
  src/main/java/com/iu/kmi/test/AuftragsPositionTest.java
Labels: G_BDK

#17 Lager Test
  src/main/java/com/iu/kmi/test/LagerTest.java
Labels: feature, G_SDK

#18 initial Debitor and DebitorTest class
  src/main/java/com/iu/kmi/entities/Debitor.java
  src/main/java/com/iu/kmi/test/DebitorTest.java
Labels: feature, G_SDK

#19 Class Lagerbestand & LagerbestandTest
  src/main/java/com/iu/kmi/entities/Lagerbestand.java
  src/main/java/com/iu/kmi/test/LagerbestandTest.java
Labels: feature, G_BDK

#27 Improved ORM to work with latest RM
  pom.xml
  src/main/java/com/iu/kmi/KmiSystem.java
  src/main/java/com/iu/kmi/database/DatabaseConnection.java
  src/main/java/com/iu/kmi/database/annotations/Id.java
  src/main/java/com/iu/kmi/database/orm/DataORM.java
  src/main/java/com/iu/kmi/database/orm/query/BaseQuery.java
  src/main/java/com/iu/kmi/database/orm/query/FindByFieldQuery.java
  src/main/java/com/iu/kmi/database/orm/query/FindByIdQuery.java
  src/main/java/com/iu/kmi/database/repository/Repository.java
  src/main/java/com/iu/kmi/database/repository/RepositoryProxy.java
Labels: bug, G_DB

#30 Fixed imports
  .gitignore
  .idea/misc.xml
  pom.xml
  src/main/java/com/iu/kmi/KmiSystem.java
  src/main/java/com/iu/kmi/test/AuftragsPositionTest.java
  src/main/java/com/iu/kmi/test/DebitorTest.java
  src/main/java/com/iu/kmi/test/KonditionTest.java
  src/main/java/com/iu/kmi/test/KundeTest.java
  src/main/java/com/iu/kmi/test/LagerTest.java
  src/main/java/com/iu/kmi/test/LagerbestandTest.java
  src/main/java/com/iu/kmi/test/MaterialTest.java
Labels: bug

#26 Angepasste Angebotsklasse mit Test
  src/main/java/com/iu/kmi/entities/Angebot.java
  src/main/java/com/iu/kmi/test/AngebotTest.java
Labels: G_BDK

#32 Added full support for composite-primary-keys
  src/main/java/com/iu/kmi/database/orm/DataORM.java
  src/main/java/com/iu/kmi/database/orm/query/BaseQuery.java
  src/main/java/com/iu/kmi/database/orm/query/DeleteQuery.java
  src/main/java/com/iu/kmi/database/orm/query/FindByIdQuery.java
  src/main/java/com/iu/kmi/database/orm/query/UpdateQuery.java
  src/main/java/com/iu/kmi/database/repository/Repository.java
  src/main/java/com/iu/kmi/database/repository/RepositoryProxy.java
Labels: feature, G_DB

#24 added save option to DebitorGUI
  src/main/java/com/iu/kmi/entities/Debitor.java
  src/main/java/com/iu/kmi/layout/DebitorInterface.java
  src/main/java/com/iu/kmi/repositories/DebitorRepository.java
Labels: feature, G_SDK

#38 Bugfix orm - Update InsertQuery.java
  src/main/java/com/iu/kmi/database/orm/query/InsertQuery.java
Labels: bug

#42 Adresse Repository erstellen
  src/main/java/com/iu/kmi/repositories/AdresseRepository.java
Labels: feature, G_BDK

#40 Kunde Repository erstellen
  src/main/java/com/iu/kmi/repositories/KundeRepository.java
Labels: feature, G_BDK

#43 Update lager/lagerbestand
  src/main/java/com/iu/kmi/entities/Lager.java
  src/main/java/com/iu/kmi/entities/Lagerbestand.java
  src/main/java/com/iu/kmi/repositories/LagerRepository.java
  src/main/java/com/iu/kmi/repositories/LagerbestandRepository.java
  src/main/java/com/iu/kmi/test/LagerTest.java
Labels: feature, G_SDK, G_BDK
